// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Course struct {
	CourseID         uuid.UUID
	CourseCode       string
	CourseTitle      string
	CourseCreditUnit int32
	CourseDuration   int32
	DepartmentID     uuid.UUID
	UniversityID     uuid.UUID
	LecturerID       uuid.NullUUID
	SessionsPerWeek  int32
	Level            int32
	Semester         string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type CoursesLecturer struct {
	CourseID   uuid.UUID
	LecturerID uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type CoursesPossibleVenue struct {
	CourseID     uuid.UUID
	VenueID      uuid.UUID
	UniversityID uuid.NullUUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type CurrentDean struct {
	DeanID       uuid.UUID
	LecturerID   uuid.NullUUID
	FacultyID    uuid.NullUUID
	UniversityID uuid.NullUUID
	StartDate    time.Time
	EndDate      sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type CurrentHod struct {
	HodID        uuid.UUID
	LecturerID   uuid.NullUUID
	DepartmentID uuid.NullUUID
	UniversityID uuid.NullUUID
	StartDate    time.Time
	EndDate      sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type DeanWaitingList struct {
	WaitID            uuid.UUID
	LecturerID        uuid.UUID
	PotentialFaculty  string
	AdditionalMessage sql.NullString
	UniversityID      uuid.UUID
	Approved          sql.NullBool
}

type Department struct {
	DepartmentID   uuid.UUID
	DepartmentName string
	DepartmentCode sql.NullString
	FacultyID      uuid.UUID
	UniversityID   uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type DeptVenue struct {
	VenueID      uuid.UUID
	DepartmentID uuid.UUID
	UniversityID uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Faculty struct {
	FacultyID    uuid.UUID
	FacultyName  string
	FacultyCode  sql.NullString
	UniversityID uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type FacultyVenue struct {
	VenueID      uuid.UUID
	FacultyID    uuid.UUID
	UniversityID uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type HodWaitingList struct {
	WaitID              uuid.UUID
	LecturerID          uuid.UUID
	PotentialDepartment string
	AdditionalMessage   sql.NullString
	UniversityID        uuid.UUID
	FacultyID           uuid.UUID
	Approved            sql.NullBool
}

type Lecturer struct {
	LecturerID           uuid.UUID
	LecturerFirstName    string
	LecturerLastName     string
	LecturerMiddleName   sql.NullString
	LecturerEmail        string
	LecturerPassword     string
	LecturerPhoneNumber  sql.NullString
	LecturerProfilePic   sql.NullString
	LecturerStaffID      sql.NullString
	LecturerUniversityID uuid.NullUUID
	LecturerFacultyID    uuid.NullUUID
	LecturerDepartmentID uuid.NullUUID
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type LecturerUnavailability struct {
	ID         uuid.UUID
	LecturerID uuid.UUID
	Day        string
	StartTime  time.Time
	EndTime    time.Time
	Reason     sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type LecturerWaitingList struct {
	WaitID            uuid.UUID
	LecturerID        uuid.UUID
	AdditionalMessage sql.NullString
	UniversityID      uuid.UUID
	FacultyID         uuid.UUID
	DepartmentID      uuid.UUID
	Approved          sql.NullBool
}

type Otp struct {
	OtpID     uuid.UUID
	Otp       string
	ExpiresAt time.Time
	Email     string
	UserType  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RefreshToken struct {
	TokenID      uuid.UUID
	RefreshToken string
	ExpiresAt    time.Time
	UserID       uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	IsRevoked    sql.NullBool
}

type Student struct {
	StudentID           uuid.UUID
	StudentFirstName    string
	StudentLastName     string
	StudentMiddleName   sql.NullString
	StudentEmail        string
	StudentPassword     string
	StudentPhoneNumber  sql.NullString
	StudentProfilePic   sql.NullString
	StudentRegNo        sql.NullString
	StudentLevel        sql.NullInt32
	StudentUniversityID uuid.NullUUID
	StudentFacultyID    uuid.NullUUID
	StudentDepartmentID uuid.NullUUID
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type StudentCoursesOffered struct {
	StudentID uuid.UUID
	CourseID  uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type University struct {
	UniversityID   uuid.UUID
	UniversityName string
	UniversityLogo sql.NullString
	UniversityAbbr sql.NullString
	Email          string
	Website        sql.NullString
	PhoneNumber    string
	UniversityAddr sql.NullString
	CurrentSession sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type UniversityAdmin struct {
	AdminID          uuid.UUID
	AdminFirstName   string
	AdminLastName    string
	AdminMiddleName  sql.NullString
	AdminEmail       string
	AdminPassword    string
	AdminPhoneNumber sql.NullString
	AdminStaffCard   sql.NullString
	AdminNumber      sql.NullString
	UniversityID     uuid.NullUUID
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Venue struct {
	VenueID        uuid.UUID
	VenueName      string
	VenueLongitude sql.NullFloat64
	VenueLatitude  sql.NullFloat64
	Location       sql.NullString
	VenueImage     sql.NullString
	Capacity       int32
	UniversityID   uuid.UUID
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type VenueUnavailability struct {
	ID           uuid.UUID
	VenueID      uuid.NullUUID
	Reason       sql.NullString
	UniversityID uuid.UUID
	Day          sql.NullString
	StartTime    sql.NullTime
	EndTime      sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
