// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (RefreshToken, error)
	ApproveDean(ctx context.Context, waitID pgtype.UUID) (DeanWaitingList, error)
	ApproveHod(ctx context.Context, waitID pgtype.UUID) (HodWaitingList, error)
	ApproveLecturer(ctx context.Context, waitID pgtype.UUID) (LecturerWaitingList, error)
	CheckAndReturnToken(ctx context.Context, userID pgtype.UUID) (CheckAndReturnTokenRow, error)
	CheckDeanConfirmation(ctx context.Context, waitID pgtype.UUID) (CheckDeanConfirmationRow, error)
	CheckDeanConfirmationWithLecturerId(ctx context.Context, lecturerID pgtype.UUID) (CheckDeanConfirmationWithLecturerIdRow, error)
	CheckHodConfirmation(ctx context.Context, waitID pgtype.UUID) (CheckHodConfirmationRow, error)
	CheckHodConfirmationWithLecturerId(ctx context.Context, lecturerID pgtype.UUID) (CheckHodConfirmationWithLecturerIdRow, error)
	CheckLecturerConfirmation(ctx context.Context, waitID pgtype.UUID) (CheckLecturerConfirmationRow, error)
	CountCohortsForOneUni(ctx context.Context, cohortUniversityID pgtype.UUID) (int64, error)
	CountDepartmentLecturers(ctx context.Context, arg CountDepartmentLecturersParams) (int64, error)
	CountFacultyLecturers(ctx context.Context, arg CountFacultyLecturersParams) (int64, error)
	CountTotalCohorts(ctx context.Context, cohortUniversityID pgtype.UUID) (int64, error)
	CountTotalCourses(ctx context.Context, universityID pgtype.UUID) (int64, error)
	CountTotalLecturers(ctx context.Context, lecturerUniversityID pgtype.UUID) (int64, error)
	CountVenuesForDepartment(ctx context.Context, arg CountVenuesForDepartmentParams) (int64, error)
	CountVenuesForUni(ctx context.Context, universityID pgtype.UUID) (int64, error)
	CountVenuesforFaculty(ctx context.Context, arg CountVenuesforFacultyParams) (int64, error)
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error)
	CreateCohort(ctx context.Context, arg CreateCohortParams) (Cohort, error)
	CreateCohortCourse(ctx context.Context, arg CreateCohortCourseParams) (CohortCoursesOffered, error)
	CreateCohortCoursesOffered(ctx context.Context, arg CreateCohortCoursesOfferedParams) (CohortCoursesOffered, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateDean(ctx context.Context, arg CreateDeanParams) (CurrentDean, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateFaculty(ctx context.Context, arg CreateFacultyParams) (Faculty, error)
	CreateHod(ctx context.Context, arg CreateHodParams) (CurrentHod, error)
	CreateLecturerUnavailability(ctx context.Context, arg CreateLecturerUnavailabilityParams) error
	CreateSessionPlacements(ctx context.Context, arg CreateSessionPlacementsParams) (SessionPlacement, error)
	CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	CreateVenueUnavailablity(ctx context.Context, arg CreateVenueUnavailablityParams) error
	DeleteCourse(ctx context.Context, courseID pgtype.UUID) error
	DeleteCoursePossibleVenue(ctx context.Context, arg DeleteCoursePossibleVenueParams) error
	DeleteRefreshToken(ctx context.Context, userID pgtype.UUID) (RefreshToken, error)
	DeprecateLatestCandidate(ctx context.Context, universityID pgtype.UUID) error
	// -- name: FetchCoursesForACohort :many
	// SELECT
	//     cohort_id
	// FROM cohort_courses_offered
	// WHERE cohort_id = $1
	// AND university_id = $2;
	FetchAllCourses(ctx context.Context, universityID pgtype.UUID) ([]FetchAllCoursesRow, error)
	FetchApprovedLecturersInDepartment(ctx context.Context, departmentID pgtype.UUID) ([]FetchApprovedLecturersInDepartmentRow, error)
	FetchCohortDetail(ctx context.Context, cohortID pgtype.UUID) (FetchCohortDetailRow, error)
	FetchCohortsForADepartment(ctx context.Context, cohortDepartmentID pgtype.UUID) ([]FetchCohortsForADepartmentRow, error)
	FetchCoursePossibleVenues(ctx context.Context, courseID pgtype.UUID) ([]FetchCoursePossibleVenuesRow, error)
	FetchLecturerUnavailability(ctx context.Context, lecturerID pgtype.UUID) ([]FetchLecturerUnavailabilityRow, error)
	GetCohortSessionsInCurrentTimetable(ctx context.Context, arg GetCohortSessionsInCurrentTimetableParams) ([]GetCohortSessionsInCurrentTimetableRow, error)
	GetStudentTimetableSessions(ctx context.Context, studentID pgtype.UUID) ([]GetStudentTimetableSessionsRow, error)
	InsertCurrentDean(ctx context.Context, arg InsertCurrentDeanParams) (CurrentDean, error)
	InsertCurrentHod(ctx context.Context, arg InsertCurrentHodParams) (CurrentHod, error)
	InsertOtp(ctx context.Context, arg InsertOtpParams) (Otp, error)
	RegisterLecturer(ctx context.Context, arg RegisterLecturerParams) (Lecturer, error)
	RegisterStudent(ctx context.Context, arg RegisterStudentParams) (Student, error)
	RegisterUniversityAdmin(ctx context.Context, arg RegisterUniversityAdminParams) (UniversityAdmin, error)
	RemoveStudentCourse(ctx context.Context, arg RemoveStudentCourseParams) (StudentCoursesOffered, error)
	RequestDeanConfirmation(ctx context.Context, arg RequestDeanConfirmationParams) (DeanWaitingList, error)
	RequestHodConfirmation(ctx context.Context, arg RequestHodConfirmationParams) (HodWaitingList, error)
	RequestLecturerConfirmation(ctx context.Context, arg RequestLecturerConfirmationParams) (LecturerWaitingList, error)
	RestoreCurrentCandidate(ctx context.Context, universityID pgtype.UUID) error
	RetrieveAdmin(ctx context.Context, adminID pgtype.UUID) (RetrieveAdminRow, error)
	RetrieveAdminEmail(ctx context.Context, adminEmail string) (RetrieveAdminEmailRow, error)
	RetrieveAllCohorts(ctx context.Context, cohortUniversityID pgtype.UUID) ([]Cohort, error)
	RetrieveAllCourses(ctx context.Context, universityID pgtype.UUID) ([]RetrieveAllCoursesRow, error)
	RetrieveAllCoursesAndTheirVenueIds(ctx context.Context, universityID pgtype.UUID) ([]RetrieveAllCoursesAndTheirVenueIdsRow, error)
	RetrieveAllUniversities(ctx context.Context) ([]University, error)
	RetrieveAllVenues(ctx context.Context, universityID pgtype.UUID) ([]RetrieveAllVenuesRow, error)
	RetrieveCohortsForAllCourses(ctx context.Context, universityID pgtype.UUID) ([]RetrieveCohortsForAllCoursesRow, error)
	RetrieveCoursesForACohort(ctx context.Context, cohortID pgtype.UUID) ([]RetrieveCoursesForACohortRow, error)
	RetrieveCoursesForADepartment(ctx context.Context, arg RetrieveCoursesForADepartmentParams) ([]RetrieveCoursesForADepartmentRow, error)
	RetrieveDean(ctx context.Context, deanID pgtype.UUID) (RetrieveDeanRow, error)
	RetrieveDeptsForAFaculty(ctx context.Context, arg RetrieveDeptsForAFacultyParams) ([]Department, error)
	RetrieveFacultiesForAUni(ctx context.Context, universityID pgtype.UUID) ([]Faculty, error)
	RetrieveHod(ctx context.Context, hodID pgtype.UUID) (RetrieveHodRow, error)
	RetrieveLecturerEmail(ctx context.Context, lecturerEmail string) (RetrieveLecturerEmailRow, error)
	RetrieveLecturersForDepartment(ctx context.Context, arg RetrieveLecturersForDepartmentParams) ([]RetrieveLecturersForDepartmentRow, error)
	RetrieveLecturersForFaculty(ctx context.Context, arg RetrieveLecturersForFacultyParams) ([]RetrieveLecturersForFacultyRow, error)
	RetrieveOtp(ctx context.Context, email string) (RetrieveOtpRow, error)
	RetrievePendingDeans(ctx context.Context, universityID pgtype.UUID) ([]DeanWaitingList, error)
	RetrievePendingHods(ctx context.Context, arg RetrievePendingHodsParams) ([]HodWaitingList, error)
	RetrievePendingLecturers(ctx context.Context, arg RetrievePendingLecturersParams) ([]LecturerWaitingList, error)
	RetrieveStudentEmail(ctx context.Context, studentEmail string) (RetrieveStudentEmailRow, error)
	RetrieveTotalLecturerUnavailability(ctx context.Context, lecturerUniversityID pgtype.UUID) ([]RetrieveTotalLecturerUnavailabilityRow, error)
	RetrieveTotalLecturers(ctx context.Context, lecturerUniversityID pgtype.UUID) ([]RetrieveTotalLecturersRow, error)
	RetrieveTotalVenueUnavailability(ctx context.Context, universityID pgtype.UUID) ([]RetrieveTotalVenueUnavailabilityRow, error)
	RetrieveUniversitiesWithLimit(ctx context.Context, limit int32) ([]University, error)
	RevokeRefreshToken(ctx context.Context, userID pgtype.UUID) (RefreshToken, error)
	SetCourseLecturers(ctx context.Context, arg SetCourseLecturersParams) (CoursesLecturer, error)
	SetCoursePossibleVenue(ctx context.Context, arg SetCoursePossibleVenueParams) error
	SetDepartmentVenue(ctx context.Context, arg SetDepartmentVenueParams) error
	SetFacultyVenue(ctx context.Context, arg SetFacultyVenueParams) error
	SetStudentCourse(ctx context.Context, arg SetStudentCourseParams) (StudentCoursesOffered, error)
	UpdateAdminInfo(ctx context.Context, arg UpdateAdminInfoParams) (UniversityAdmin, error)
	UpdateCohort(ctx context.Context, arg UpdateCohortParams) (Cohort, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateCourseLecturers(ctx context.Context, arg UpdateCourseLecturersParams) (CoursesLecturer, error)
	UpdateDean(ctx context.Context, arg UpdateDeanParams) (CurrentDean, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateFaculty(ctx context.Context, arg UpdateFacultyParams) (Faculty, error)
	UpdateHod(ctx context.Context, arg UpdateHodParams) (CurrentHod, error)
	UpdateLecturerInfo(ctx context.Context, arg UpdateLecturerInfoParams) (Lecturer, error)
	UpdateLecturerUnavailability(ctx context.Context, arg UpdateLecturerUnavailabilityParams) error
	UpdateLecturerUniversityId(ctx context.Context, arg UpdateLecturerUniversityIdParams) error
	UpdateOtp(ctx context.Context, arg UpdateOtpParams) (Otp, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error)
	UpdateStudentInfo(ctx context.Context, arg UpdateStudentInfoParams) (Student, error)
	UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) (University, error)
}

// var _ Querier = (*Queries)(nil)
