// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addRefreshToken = `-- name: AddRefreshToken :one
INSERT INTO refresh_tokens(
    refresh_token, expires_at, user_id
) VALUES (
    $1, $2, $3
)
RETURNING token_id, refresh_token, expires_at, user_id, created_at, updated_at, is_revoked
`

type AddRefreshTokenParams struct {
	RefreshToken string
	ExpiresAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, addRefreshToken, arg.RefreshToken, arg.ExpiresAt, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRevoked,
	)
	return i, err
}

const approveDean = `-- name: ApproveDean :one
UPDATE dean_waiting_list
SET approved = TRUE
WHERE wait_id = $1
RETURNING wait_id, lecturer_id, potential_faculty, additional_message, university_id, approved
`

func (q *Queries) ApproveDean(ctx context.Context, waitID uuid.UUID) (DeanWaitingList, error) {
	row := q.db.QueryRowContext(ctx, approveDean, waitID)
	var i DeanWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.PotentialFaculty,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.Approved,
	)
	return i, err
}

const approveHod = `-- name: ApproveHod :one
UPDATE hod_waiting_list
SET approved = TRUE
WHERE wait_id = $1
RETURNING wait_id, lecturer_id, potential_department, additional_message, university_id, faculty_id, approved
`

func (q *Queries) ApproveHod(ctx context.Context, waitID uuid.UUID) (HodWaitingList, error) {
	row := q.db.QueryRowContext(ctx, approveHod, waitID)
	var i HodWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.PotentialDepartment,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.FacultyID,
		&i.Approved,
	)
	return i, err
}

const approveLecturer = `-- name: ApproveLecturer :one
UPDATE lecturer_waiting_list
SET approved = TRUE
WHERE wait_id = $1
RETURNING wait_id, lecturer_id, additional_message, university_id, faculty_id, department_id, approved
`

func (q *Queries) ApproveLecturer(ctx context.Context, waitID uuid.UUID) (LecturerWaitingList, error) {
	row := q.db.QueryRowContext(ctx, approveLecturer, waitID)
	var i LecturerWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.FacultyID,
		&i.DepartmentID,
		&i.Approved,
	)
	return i, err
}

const checkAndReturnToken = `-- name: CheckAndReturnToken :one
SELECT refresh_token,expires_at,user_id,is_revoked
FROM refresh_tokens
WHERE user_id = $1
`

type CheckAndReturnTokenRow struct {
	RefreshToken string
	ExpiresAt    time.Time
	UserID       uuid.UUID
	IsRevoked    sql.NullBool
}

func (q *Queries) CheckAndReturnToken(ctx context.Context, userID uuid.UUID) (CheckAndReturnTokenRow, error) {
	row := q.db.QueryRowContext(ctx, checkAndReturnToken, userID)
	var i CheckAndReturnTokenRow
	err := row.Scan(
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.IsRevoked,
	)
	return i, err
}

const createDean = `-- name: CreateDean :one
INSERT INTO current_dean(
    lecturer_id,faculty_id,university_id,start_date,end_date
)VALUES(
    $1,$2,$3,$4,$5
)
RETURNING dean_id, lecturer_id, faculty_id, university_id, start_date, end_date, created_at, updated_at
`

type CreateDeanParams struct {
	LecturerID   uuid.NullUUID
	FacultyID    uuid.NullUUID
	UniversityID uuid.NullUUID
	StartDate    time.Time
	EndDate      sql.NullTime
}

func (q *Queries) CreateDean(ctx context.Context, arg CreateDeanParams) (CurrentDean, error) {
	row := q.db.QueryRowContext(ctx, createDean,
		arg.LecturerID,
		arg.FacultyID,
		arg.UniversityID,
		arg.StartDate,
		arg.EndDate,
	)
	var i CurrentDean
	err := row.Scan(
		&i.DeanID,
		&i.LecturerID,
		&i.FacultyID,
		&i.UniversityID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments(
    department_name,department_code,faculty_id,university_id
)VALUES(
    $1,$2,$3,$4
)
RETURNING department_id, department_name, department_code, faculty_id, university_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	DepartmentName string
	DepartmentCode sql.NullString
	FacultyID      uuid.UUID
	UniversityID   uuid.UUID
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment,
		arg.DepartmentName,
		arg.DepartmentCode,
		arg.FacultyID,
		arg.UniversityID,
	)
	var i Department
	err := row.Scan(
		&i.DepartmentID,
		&i.DepartmentName,
		&i.DepartmentCode,
		&i.FacultyID,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFaculty = `-- name: CreateFaculty :one
INSERT INTO faculties(
    faculty_name,faculty_code,university_id
)VALUES(
    $1,$2,$3
)
RETURNING faculty_id, faculty_name, faculty_code, university_id, created_at, updated_at
`

type CreateFacultyParams struct {
	FacultyName  string
	FacultyCode  sql.NullString
	UniversityID uuid.UUID
}

func (q *Queries) CreateFaculty(ctx context.Context, arg CreateFacultyParams) (Faculty, error) {
	row := q.db.QueryRowContext(ctx, createFaculty, arg.FacultyName, arg.FacultyCode, arg.UniversityID)
	var i Faculty
	err := row.Scan(
		&i.FacultyID,
		&i.FacultyName,
		&i.FacultyCode,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHod = `-- name: CreateHod :one
INSERT INTO current_hod(
    lecturer_id,department_id,university_id,start_date,end_date
)VALUES(
    $1,$2,$3,$4,$5
)
RETURNING hod_id, lecturer_id, department_id, university_id, start_date, end_date, created_at, updated_at
`

type CreateHodParams struct {
	LecturerID   uuid.NullUUID
	DepartmentID uuid.NullUUID
	UniversityID uuid.NullUUID
	StartDate    time.Time
	EndDate      sql.NullTime
}

func (q *Queries) CreateHod(ctx context.Context, arg CreateHodParams) (CurrentHod, error) {
	row := q.db.QueryRowContext(ctx, createHod,
		arg.LecturerID,
		arg.DepartmentID,
		arg.UniversityID,
		arg.StartDate,
		arg.EndDate,
	)
	var i CurrentHod
	err := row.Scan(
		&i.HodID,
		&i.LecturerID,
		&i.DepartmentID,
		&i.UniversityID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUniversity = `-- name: CreateUniversity :one
INSERT INTO universities(
    university_name,university_logo,university_abbr,email,website,phone_number,university_addr,current_session
)VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8
) RETURNING university_id, university_name, university_logo, university_abbr, email, website, phone_number, university_addr, current_session, created_at, updated_at
`

type CreateUniversityParams struct {
	UniversityName string
	UniversityLogo sql.NullString
	UniversityAbbr sql.NullString
	Email          string
	Website        sql.NullString
	PhoneNumber    string
	UniversityAddr sql.NullString
	CurrentSession sql.NullString
}

func (q *Queries) CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error) {
	row := q.db.QueryRowContext(ctx, createUniversity,
		arg.UniversityName,
		arg.UniversityLogo,
		arg.UniversityAbbr,
		arg.Email,
		arg.Website,
		arg.PhoneNumber,
		arg.UniversityAddr,
		arg.CurrentSession,
	)
	var i University
	err := row.Scan(
		&i.UniversityID,
		&i.UniversityName,
		&i.UniversityLogo,
		&i.UniversityAbbr,
		&i.Email,
		&i.Website,
		&i.PhoneNumber,
		&i.UniversityAddr,
		&i.CurrentSession,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :one
DELETE FROM refresh_tokens
WHERE user_id = $1
RETURNING token_id, refresh_token, expires_at, user_id, created_at, updated_at, is_revoked
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, deleteRefreshToken, userID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRevoked,
	)
	return i, err
}

const insertOtp = `-- name: InsertOtp :one
INSERT INTO otps(
    otp,expires_at,email,user_type
)VALUES(
    $1,$2,$3,$4
)
RETURNING otp_id, otp, expires_at, email, user_type, created_at, updated_at
`

type InsertOtpParams struct {
	Otp       string
	ExpiresAt time.Time
	Email     string
	UserType  string
}

func (q *Queries) InsertOtp(ctx context.Context, arg InsertOtpParams) (Otp, error) {
	row := q.db.QueryRowContext(ctx, insertOtp,
		arg.Otp,
		arg.ExpiresAt,
		arg.Email,
		arg.UserType,
	)
	var i Otp
	err := row.Scan(
		&i.OtpID,
		&i.Otp,
		&i.ExpiresAt,
		&i.Email,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerLecturer = `-- name: RegisterLecturer :one
INSERT INTO lecturers(
    lecturer_first_name,lecturer_last_name,lecturer_email,lecturer_password
) VALUES(
    $1,$2,$3,$4
)
RETURNING lecturer_id, lecturer_first_name, lecturer_last_name, lecturer_middle_name, lecturer_email, lecturer_password, lecturer_phone_number, lecturer_profile_pic, lecturer_staff_id, lecturer_university_id, lecturer_faculty_id, lecturer_department_id, created_at, updated_at
`

type RegisterLecturerParams struct {
	LecturerFirstName string
	LecturerLastName  string
	LecturerEmail     string
	LecturerPassword  string
}

func (q *Queries) RegisterLecturer(ctx context.Context, arg RegisterLecturerParams) (Lecturer, error) {
	row := q.db.QueryRowContext(ctx, registerLecturer,
		arg.LecturerFirstName,
		arg.LecturerLastName,
		arg.LecturerEmail,
		arg.LecturerPassword,
	)
	var i Lecturer
	err := row.Scan(
		&i.LecturerID,
		&i.LecturerFirstName,
		&i.LecturerLastName,
		&i.LecturerMiddleName,
		&i.LecturerEmail,
		&i.LecturerPassword,
		&i.LecturerPhoneNumber,
		&i.LecturerProfilePic,
		&i.LecturerStaffID,
		&i.LecturerUniversityID,
		&i.LecturerFacultyID,
		&i.LecturerDepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerStudent = `-- name: RegisterStudent :one
INSERT INTO students(
    student_first_name,student_last_name,student_email,student_password
) VALUES (
    $1,$2,$3,$4
)
RETURNING student_id, student_first_name, student_last_name, student_middle_name, student_email, student_password, student_phone_number, student_profile_pic, student_reg_no, student_level, student_university_id, student_faculty_id, student_department_id, created_at, updated_at
`

type RegisterStudentParams struct {
	StudentFirstName string
	StudentLastName  string
	StudentEmail     string
	StudentPassword  string
}

func (q *Queries) RegisterStudent(ctx context.Context, arg RegisterStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, registerStudent,
		arg.StudentFirstName,
		arg.StudentLastName,
		arg.StudentEmail,
		arg.StudentPassword,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentMiddleName,
		&i.StudentEmail,
		&i.StudentPassword,
		&i.StudentPhoneNumber,
		&i.StudentProfilePic,
		&i.StudentRegNo,
		&i.StudentLevel,
		&i.StudentUniversityID,
		&i.StudentFacultyID,
		&i.StudentDepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerUniversityAdmin = `-- name: RegisterUniversityAdmin :one
INSERT INTO university_admin(
    admin_first_name,admin_last_name,admin_email,admin_password
) VALUES (
    $1,$2,$3,$4
)
RETURNING admin_id, admin_first_name, admin_last_name, admin_middle_name, admin_email, admin_password, admin_phone_number, admin_staff_card, admin_number, university_id, created_at, updated_at
`

type RegisterUniversityAdminParams struct {
	AdminFirstName string
	AdminLastName  string
	AdminEmail     string
	AdminPassword  string
}

func (q *Queries) RegisterUniversityAdmin(ctx context.Context, arg RegisterUniversityAdminParams) (UniversityAdmin, error) {
	row := q.db.QueryRowContext(ctx, registerUniversityAdmin,
		arg.AdminFirstName,
		arg.AdminLastName,
		arg.AdminEmail,
		arg.AdminPassword,
	)
	var i UniversityAdmin
	err := row.Scan(
		&i.AdminID,
		&i.AdminFirstName,
		&i.AdminLastName,
		&i.AdminMiddleName,
		&i.AdminEmail,
		&i.AdminPassword,
		&i.AdminPhoneNumber,
		&i.AdminStaffCard,
		&i.AdminNumber,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestDeanConfirmation = `-- name: RequestDeanConfirmation :one
INSERT INTO dean_waiting_list(
    lecturer_id,potential_faculty,additional_message,university_id
)
VALUES(
    $1,$2,$3,$4
)
RETURNING wait_id, lecturer_id, potential_faculty, additional_message, university_id, approved
`

type RequestDeanConfirmationParams struct {
	LecturerID        uuid.UUID
	PotentialFaculty  string
	AdditionalMessage sql.NullString
	UniversityID      uuid.UUID
}

func (q *Queries) RequestDeanConfirmation(ctx context.Context, arg RequestDeanConfirmationParams) (DeanWaitingList, error) {
	row := q.db.QueryRowContext(ctx, requestDeanConfirmation,
		arg.LecturerID,
		arg.PotentialFaculty,
		arg.AdditionalMessage,
		arg.UniversityID,
	)
	var i DeanWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.PotentialFaculty,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.Approved,
	)
	return i, err
}

const requestHodConfirmation = `-- name: RequestHodConfirmation :one
INSERT INTO hod_waiting_list(
    lecturer_id,potential_department,additional_message,university_id,faculty_id
)
VALUES(
    $1,$2,$3,$4,$5
)
RETURNING wait_id, lecturer_id, potential_department, additional_message, university_id, faculty_id, approved
`

type RequestHodConfirmationParams struct {
	LecturerID          uuid.UUID
	PotentialDepartment string
	AdditionalMessage   sql.NullString
	UniversityID        uuid.UUID
	FacultyID           uuid.UUID
}

func (q *Queries) RequestHodConfirmation(ctx context.Context, arg RequestHodConfirmationParams) (HodWaitingList, error) {
	row := q.db.QueryRowContext(ctx, requestHodConfirmation,
		arg.LecturerID,
		arg.PotentialDepartment,
		arg.AdditionalMessage,
		arg.UniversityID,
		arg.FacultyID,
	)
	var i HodWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.PotentialDepartment,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.FacultyID,
		&i.Approved,
	)
	return i, err
}

const requestLecturerConfirmation = `-- name: RequestLecturerConfirmation :one
INSERT INTO lecturer_waiting_list(
    lecturer_id,additional_message,university_id,faculty_id,department_id
)
VALUES(
    $1,$2,$3,$4,$5
)
RETURNING wait_id, lecturer_id, additional_message, university_id, faculty_id, department_id, approved
`

type RequestLecturerConfirmationParams struct {
	LecturerID        uuid.UUID
	AdditionalMessage sql.NullString
	UniversityID      uuid.UUID
	FacultyID         uuid.UUID
	DepartmentID      uuid.UUID
}

func (q *Queries) RequestLecturerConfirmation(ctx context.Context, arg RequestLecturerConfirmationParams) (LecturerWaitingList, error) {
	row := q.db.QueryRowContext(ctx, requestLecturerConfirmation,
		arg.LecturerID,
		arg.AdditionalMessage,
		arg.UniversityID,
		arg.FacultyID,
		arg.DepartmentID,
	)
	var i LecturerWaitingList
	err := row.Scan(
		&i.WaitID,
		&i.LecturerID,
		&i.AdditionalMessage,
		&i.UniversityID,
		&i.FacultyID,
		&i.DepartmentID,
		&i.Approved,
	)
	return i, err
}

const retrieveAdminEmail = `-- name: RetrieveAdminEmail :one
SELECT admin_id,admin_email,admin_password FROM university_admin WHERE admin_email = $1
`

type RetrieveAdminEmailRow struct {
	AdminID       uuid.UUID
	AdminEmail    string
	AdminPassword string
}

func (q *Queries) RetrieveAdminEmail(ctx context.Context, adminEmail string) (RetrieveAdminEmailRow, error) {
	row := q.db.QueryRowContext(ctx, retrieveAdminEmail, adminEmail)
	var i RetrieveAdminEmailRow
	err := row.Scan(&i.AdminID, &i.AdminEmail, &i.AdminPassword)
	return i, err
}

const retrieveAllUniversities = `-- name: RetrieveAllUniversities :many
SELECT university_id, university_name, university_logo, university_abbr, email, website, phone_number, university_addr, current_session, created_at, updated_at FROM universities
`

func (q *Queries) RetrieveAllUniversities(ctx context.Context) ([]University, error) {
	rows, err := q.db.QueryContext(ctx, retrieveAllUniversities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.UniversityID,
			&i.UniversityName,
			&i.UniversityLogo,
			&i.UniversityAbbr,
			&i.Email,
			&i.Website,
			&i.PhoneNumber,
			&i.UniversityAddr,
			&i.CurrentSession,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveDeptsForAFaculty = `-- name: RetrieveDeptsForAFaculty :many
SELECT department_id, department_name, department_code, faculty_id, university_id, created_at, updated_at FROM departments
WHERE faculty_id = $1 AND university_id = $2
`

type RetrieveDeptsForAFacultyParams struct {
	FacultyID    uuid.UUID
	UniversityID uuid.UUID
}

func (q *Queries) RetrieveDeptsForAFaculty(ctx context.Context, arg RetrieveDeptsForAFacultyParams) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, retrieveDeptsForAFaculty, arg.FacultyID, arg.UniversityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.DepartmentID,
			&i.DepartmentName,
			&i.DepartmentCode,
			&i.FacultyID,
			&i.UniversityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveFacultiesForAUni = `-- name: RetrieveFacultiesForAUni :many
SELECT faculty_id, faculty_name, faculty_code, university_id, created_at, updated_at FROM faculties
WHERE university_id = $1
`

func (q *Queries) RetrieveFacultiesForAUni(ctx context.Context, universityID uuid.UUID) ([]Faculty, error) {
	rows, err := q.db.QueryContext(ctx, retrieveFacultiesForAUni, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Faculty
	for rows.Next() {
		var i Faculty
		if err := rows.Scan(
			&i.FacultyID,
			&i.FacultyName,
			&i.FacultyCode,
			&i.UniversityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveLecturerEmail = `-- name: RetrieveLecturerEmail :one
SELECT lecturer_id,lecturer_email,lecturer_password FROM lecturers WHERE lecturer_email = $1
`

type RetrieveLecturerEmailRow struct {
	LecturerID       uuid.UUID
	LecturerEmail    string
	LecturerPassword string
}

func (q *Queries) RetrieveLecturerEmail(ctx context.Context, lecturerEmail string) (RetrieveLecturerEmailRow, error) {
	row := q.db.QueryRowContext(ctx, retrieveLecturerEmail, lecturerEmail)
	var i RetrieveLecturerEmailRow
	err := row.Scan(&i.LecturerID, &i.LecturerEmail, &i.LecturerPassword)
	return i, err
}

const retrieveOtp = `-- name: RetrieveOtp :one
SELECT otp,expires_at FROM otps WHERE email = $1
`

type RetrieveOtpRow struct {
	Otp       string
	ExpiresAt time.Time
}

func (q *Queries) RetrieveOtp(ctx context.Context, email string) (RetrieveOtpRow, error) {
	row := q.db.QueryRowContext(ctx, retrieveOtp, email)
	var i RetrieveOtpRow
	err := row.Scan(&i.Otp, &i.ExpiresAt)
	return i, err
}

const retrievePendingDeans = `-- name: RetrievePendingDeans :many
SELECT wait_id, lecturer_id, potential_faculty, additional_message, university_id, approved FROM dean_waiting_list WHERE university_id = $1
`

func (q *Queries) RetrievePendingDeans(ctx context.Context, universityID uuid.UUID) ([]DeanWaitingList, error) {
	rows, err := q.db.QueryContext(ctx, retrievePendingDeans, universityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeanWaitingList
	for rows.Next() {
		var i DeanWaitingList
		if err := rows.Scan(
			&i.WaitID,
			&i.LecturerID,
			&i.PotentialFaculty,
			&i.AdditionalMessage,
			&i.UniversityID,
			&i.Approved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrievePendingHods = `-- name: RetrievePendingHods :many
SELECT wait_id, lecturer_id, potential_department, additional_message, university_id, faculty_id, approved FROM hod_waiting_list 
WHERE university_id = $1 AND faculty_id = $2
`

type RetrievePendingHodsParams struct {
	UniversityID uuid.UUID
	FacultyID    uuid.UUID
}

func (q *Queries) RetrievePendingHods(ctx context.Context, arg RetrievePendingHodsParams) ([]HodWaitingList, error) {
	rows, err := q.db.QueryContext(ctx, retrievePendingHods, arg.UniversityID, arg.FacultyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HodWaitingList
	for rows.Next() {
		var i HodWaitingList
		if err := rows.Scan(
			&i.WaitID,
			&i.LecturerID,
			&i.PotentialDepartment,
			&i.AdditionalMessage,
			&i.UniversityID,
			&i.FacultyID,
			&i.Approved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrievePendingLecturers = `-- name: RetrievePendingLecturers :many
SELECT wait_id, lecturer_id, additional_message, university_id, faculty_id, department_id, approved FROM lecturer_waiting_list
WHERE university_id = $1 AND faculty_id = $2 AND department_id = $3
`

type RetrievePendingLecturersParams struct {
	UniversityID uuid.UUID
	FacultyID    uuid.UUID
	DepartmentID uuid.UUID
}

func (q *Queries) RetrievePendingLecturers(ctx context.Context, arg RetrievePendingLecturersParams) ([]LecturerWaitingList, error) {
	rows, err := q.db.QueryContext(ctx, retrievePendingLecturers, arg.UniversityID, arg.FacultyID, arg.DepartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LecturerWaitingList
	for rows.Next() {
		var i LecturerWaitingList
		if err := rows.Scan(
			&i.WaitID,
			&i.LecturerID,
			&i.AdditionalMessage,
			&i.UniversityID,
			&i.FacultyID,
			&i.DepartmentID,
			&i.Approved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveStudentEmail = `-- name: RetrieveStudentEmail :one
SELECT student_id,student_email,student_password FROM students WHERE student_email = $1
`

type RetrieveStudentEmailRow struct {
	StudentID       uuid.UUID
	StudentEmail    string
	StudentPassword string
}

func (q *Queries) RetrieveStudentEmail(ctx context.Context, studentEmail string) (RetrieveStudentEmailRow, error) {
	row := q.db.QueryRowContext(ctx, retrieveStudentEmail, studentEmail)
	var i RetrieveStudentEmailRow
	err := row.Scan(&i.StudentID, &i.StudentEmail, &i.StudentPassword)
	return i, err
}

const retrieveUniversitiesWithLimit = `-- name: RetrieveUniversitiesWithLimit :many
SELECT university_id, university_name, university_logo, university_abbr, email, website, phone_number, university_addr, current_session, created_at, updated_at FROM universities LIMIT $1
`

func (q *Queries) RetrieveUniversitiesWithLimit(ctx context.Context, limit int32) ([]University, error) {
	rows, err := q.db.QueryContext(ctx, retrieveUniversitiesWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.UniversityID,
			&i.UniversityName,
			&i.UniversityLogo,
			&i.UniversityAbbr,
			&i.Email,
			&i.Website,
			&i.PhoneNumber,
			&i.UniversityAddr,
			&i.CurrentSession,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE user_id = $1
RETURNING token_id, refresh_token, expires_at, user_id, created_at, updated_at, is_revoked
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, userID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRevoked,
	)
	return i, err
}

const updateAdminInfo = `-- name: UpdateAdminInfo :one
UPDATE university_admin
SET admin_middle_name = $1, admin_phone_number = $2, admin_staff_card = $3, admin_number = $4, university_id = $5
WHERE admin_id = $6
RETURNING admin_id, admin_first_name, admin_last_name, admin_middle_name, admin_email, admin_password, admin_phone_number, admin_staff_card, admin_number, university_id, created_at, updated_at
`

type UpdateAdminInfoParams struct {
	AdminMiddleName  sql.NullString
	AdminPhoneNumber sql.NullString
	AdminStaffCard   sql.NullString
	AdminNumber      sql.NullString
	UniversityID     uuid.NullUUID
	AdminID          uuid.UUID
}

func (q *Queries) UpdateAdminInfo(ctx context.Context, arg UpdateAdminInfoParams) (UniversityAdmin, error) {
	row := q.db.QueryRowContext(ctx, updateAdminInfo,
		arg.AdminMiddleName,
		arg.AdminPhoneNumber,
		arg.AdminStaffCard,
		arg.AdminNumber,
		arg.UniversityID,
		arg.AdminID,
	)
	var i UniversityAdmin
	err := row.Scan(
		&i.AdminID,
		&i.AdminFirstName,
		&i.AdminLastName,
		&i.AdminMiddleName,
		&i.AdminEmail,
		&i.AdminPassword,
		&i.AdminPhoneNumber,
		&i.AdminStaffCard,
		&i.AdminNumber,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDean = `-- name: UpdateDean :one
UPDATE current_dean
SET 
    start_date = $1,
    end_date = $2
WHERE dean_id = $3
RETURNING dean_id, lecturer_id, faculty_id, university_id, start_date, end_date, created_at, updated_at
`

type UpdateDeanParams struct {
	StartDate time.Time
	EndDate   sql.NullTime
	DeanID    uuid.UUID
}

func (q *Queries) UpdateDean(ctx context.Context, arg UpdateDeanParams) (CurrentDean, error) {
	row := q.db.QueryRowContext(ctx, updateDean, arg.StartDate, arg.EndDate, arg.DeanID)
	var i CurrentDean
	err := row.Scan(
		&i.DeanID,
		&i.LecturerID,
		&i.FacultyID,
		&i.UniversityID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET 
    department_name = $1,
    department_code = $2
WHERE department_id = $3
RETURNING department_id, department_name, department_code, faculty_id, university_id, created_at, updated_at
`

type UpdateDepartmentParams struct {
	DepartmentName string
	DepartmentCode sql.NullString
	DepartmentID   uuid.UUID
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, updateDepartment, arg.DepartmentName, arg.DepartmentCode, arg.DepartmentID)
	var i Department
	err := row.Scan(
		&i.DepartmentID,
		&i.DepartmentName,
		&i.DepartmentCode,
		&i.FacultyID,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFaculty = `-- name: UpdateFaculty :one
UPDATE faculties
SET 
    faculty_name = $1,
    faculty_code = $2
WHERE faculty_id = $3
RETURNING faculty_id, faculty_name, faculty_code, university_id, created_at, updated_at
`

type UpdateFacultyParams struct {
	FacultyName string
	FacultyCode sql.NullString
	FacultyID   uuid.UUID
}

func (q *Queries) UpdateFaculty(ctx context.Context, arg UpdateFacultyParams) (Faculty, error) {
	row := q.db.QueryRowContext(ctx, updateFaculty, arg.FacultyName, arg.FacultyCode, arg.FacultyID)
	var i Faculty
	err := row.Scan(
		&i.FacultyID,
		&i.FacultyName,
		&i.FacultyCode,
		&i.UniversityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHod = `-- name: UpdateHod :one
UPDATE current_hod
SET 
    start_date = $1,
    end_date = $2
WHERE hod_id = $3
RETURNING hod_id, lecturer_id, department_id, university_id, start_date, end_date, created_at, updated_at
`

type UpdateHodParams struct {
	StartDate time.Time
	EndDate   sql.NullTime
	HodID     uuid.UUID
}

func (q *Queries) UpdateHod(ctx context.Context, arg UpdateHodParams) (CurrentHod, error) {
	row := q.db.QueryRowContext(ctx, updateHod, arg.StartDate, arg.EndDate, arg.HodID)
	var i CurrentHod
	err := row.Scan(
		&i.HodID,
		&i.LecturerID,
		&i.DepartmentID,
		&i.UniversityID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLecturerInfo = `-- name: UpdateLecturerInfo :one
UPDATE lecturers
SET lecturer_middle_name = $1, lecturer_phone_number = $2, lecturer_profile_pic = $3, lecturer_staff_id = $4, lecturer_university_id = $5, lecturer_faculty_id = $6, lecturer_department_id = $7
WHERE lecturer_id = $8
RETURNING lecturer_id, lecturer_first_name, lecturer_last_name, lecturer_middle_name, lecturer_email, lecturer_password, lecturer_phone_number, lecturer_profile_pic, lecturer_staff_id, lecturer_university_id, lecturer_faculty_id, lecturer_department_id, created_at, updated_at
`

type UpdateLecturerInfoParams struct {
	LecturerMiddleName   sql.NullString
	LecturerPhoneNumber  sql.NullString
	LecturerProfilePic   sql.NullString
	LecturerStaffID      sql.NullString
	LecturerUniversityID uuid.NullUUID
	LecturerFacultyID    uuid.NullUUID
	LecturerDepartmentID uuid.NullUUID
	LecturerID           uuid.UUID
}

func (q *Queries) UpdateLecturerInfo(ctx context.Context, arg UpdateLecturerInfoParams) (Lecturer, error) {
	row := q.db.QueryRowContext(ctx, updateLecturerInfo,
		arg.LecturerMiddleName,
		arg.LecturerPhoneNumber,
		arg.LecturerProfilePic,
		arg.LecturerStaffID,
		arg.LecturerUniversityID,
		arg.LecturerFacultyID,
		arg.LecturerDepartmentID,
		arg.LecturerID,
	)
	var i Lecturer
	err := row.Scan(
		&i.LecturerID,
		&i.LecturerFirstName,
		&i.LecturerLastName,
		&i.LecturerMiddleName,
		&i.LecturerEmail,
		&i.LecturerPassword,
		&i.LecturerPhoneNumber,
		&i.LecturerProfilePic,
		&i.LecturerStaffID,
		&i.LecturerUniversityID,
		&i.LecturerFacultyID,
		&i.LecturerDepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOtp = `-- name: UpdateOtp :one
UPDATE otps
SET otp = $1, expires_at = $2
WHERE email = $3
RETURNING otp_id, otp, expires_at, email, user_type, created_at, updated_at
`

type UpdateOtpParams struct {
	Otp       string
	ExpiresAt time.Time
	Email     string
}

func (q *Queries) UpdateOtp(ctx context.Context, arg UpdateOtpParams) (Otp, error) {
	row := q.db.QueryRowContext(ctx, updateOtp, arg.Otp, arg.ExpiresAt, arg.Email)
	var i Otp
	err := row.Scan(
		&i.OtpID,
		&i.Otp,
		&i.ExpiresAt,
		&i.Email,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
UPDATE refresh_tokens 
SET refresh_token = $1, expires_at = $2, updated_at = NOW()
WHERE user_id = $3
RETURNING token_id, refresh_token, expires_at, user_id, created_at, updated_at, is_revoked
`

type UpdateRefreshTokenParams struct {
	RefreshToken string
	ExpiresAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, updateRefreshToken, arg.RefreshToken, arg.ExpiresAt, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRevoked,
	)
	return i, err
}

const updateStudentInfo = `-- name: UpdateStudentInfo :one
UPDATE students
SET student_middle_name = $1, student_phone_number = $2, student_profile_pic = $3, student_reg_no = $4, student_level = $5, student_university_id = $6, student_faculty_id = $7, student_department_id = $8
WHERE student_id = $9
RETURNING student_id, student_first_name, student_last_name, student_middle_name, student_email, student_password, student_phone_number, student_profile_pic, student_reg_no, student_level, student_university_id, student_faculty_id, student_department_id, created_at, updated_at
`

type UpdateStudentInfoParams struct {
	StudentMiddleName   sql.NullString
	StudentPhoneNumber  sql.NullString
	StudentProfilePic   sql.NullString
	StudentRegNo        sql.NullString
	StudentLevel        sql.NullInt32
	StudentUniversityID uuid.NullUUID
	StudentFacultyID    uuid.NullUUID
	StudentDepartmentID uuid.NullUUID
	StudentID           uuid.UUID
}

func (q *Queries) UpdateStudentInfo(ctx context.Context, arg UpdateStudentInfoParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentInfo,
		arg.StudentMiddleName,
		arg.StudentPhoneNumber,
		arg.StudentProfilePic,
		arg.StudentRegNo,
		arg.StudentLevel,
		arg.StudentUniversityID,
		arg.StudentFacultyID,
		arg.StudentDepartmentID,
		arg.StudentID,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentMiddleName,
		&i.StudentEmail,
		&i.StudentPassword,
		&i.StudentPhoneNumber,
		&i.StudentProfilePic,
		&i.StudentRegNo,
		&i.StudentLevel,
		&i.StudentUniversityID,
		&i.StudentFacultyID,
		&i.StudentDepartmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUniversity = `-- name: UpdateUniversity :one
UPDATE universities
SET 
    university_name = $1, 
    university_logo = $2, 
    university_abbr = $3, 
    email = $4, 
    website = $5, 
    phone_number = $6, 
    university_addr = $7, 
    current_session = $8
WHERE university_id = $9
RETURNING university_id, university_name, university_logo, university_abbr, email, website, phone_number, university_addr, current_session, created_at, updated_at
`

type UpdateUniversityParams struct {
	UniversityName string
	UniversityLogo sql.NullString
	UniversityAbbr sql.NullString
	Email          string
	Website        sql.NullString
	PhoneNumber    string
	UniversityAddr sql.NullString
	CurrentSession sql.NullString
	UniversityID   uuid.UUID
}

func (q *Queries) UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) (University, error) {
	row := q.db.QueryRowContext(ctx, updateUniversity,
		arg.UniversityName,
		arg.UniversityLogo,
		arg.UniversityAbbr,
		arg.Email,
		arg.Website,
		arg.PhoneNumber,
		arg.UniversityAddr,
		arg.CurrentSession,
		arg.UniversityID,
	)
	var i University
	err := row.Scan(
		&i.UniversityID,
		&i.UniversityName,
		&i.UniversityLogo,
		&i.UniversityAbbr,
		&i.Email,
		&i.Website,
		&i.PhoneNumber,
		&i.UniversityAddr,
		&i.CurrentSession,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
